/*
# Create study_sessions table (single-tenant, no auth)

1. New Tables
- `study_sessions`
  - `id` (uuid, primary key)
  - `topic` (text, the study topic the user entered)
  - `input_text` (text, the raw notes/content the user pasted)
  - `flashcards` (jsonb, array of {id, front, back} objects generated by AI)
  - `quiz` (jsonb, array of {id, question, options[], answerIndex, explanation} objects)
  - `created_at` (timestamp)

2. Security
- Enable RLS on `study_sessions`.
- Single-tenant app with no sign-in: allow anon + authenticated full CRUD
  because the data is intentionally shared/public across the app instance.
*/

CREATE TABLE IF NOT EXISTS study_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  topic text NOT NULL,
  input_text text NOT NULL DEFAULT '',
  flashcards jsonb NOT NULL DEFAULT '[]'::jsonb,
  quiz jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_study_sessions" ON study_sessions;
CREATE POLICY "anon_select_study_sessions" ON study_sessions FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_study_sessions" ON study_sessions;
CREATE POLICY "anon_insert_study_sessions" ON study_sessions FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_study_sessions" ON study_sessions;
CREATE POLICY "anon_update_study_sessions" ON study_sessions FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_study_sessions" ON study_sessions;
CREATE POLICY "anon_delete_study_sessions" ON study_sessions FOR DELETE
  TO anon, authenticated USING (true);
